// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Axios: typeof import('./src/components/test/Axios.vue')['default']
    ElButt: typeof import('element-plus/es')['ElButt']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    Ele: typeof import('./src/components/test/Ele.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LessTest: typeof import('./src/components/test/LessTest.vue')['default']
    School: typeof import('./src/components/test/School.vue')['default']
    Student: typeof import('./src/components/test/Student.vue')['default']
  }
}

export { }
